#!/usr/bin/python
import os
virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON EGG CACHE'] = os.path.join(virtenv,\
'lib/python2.7/site-packages)
virtualenv = os.path.join(virtenv, 'bin/activatethis.py')
try:
        execfile(virtualenv,dict(__file__=virtualenv))
except IOError:
        pass
from run import app as application
